export default function InsightsPage() {
  return (
    <div className="min-h-screen bg-black text-white p-10">
      <h1 className="text-4xl font-bold mb-4">
        🤖 AI Career Insights
      </h1>

      <p className="text-gray-400 mb-10">
        Personalized recommendations generated by AI.
      </p>

      <div className="space-y-6">

        <div className="bg-gray-900 p-6 rounded-2xl">
          <h3 className="text-xl font-bold mb-2">
            Top Missing Skill
          </h3>
          <p>Docker & Kubernetes</p>
        </div>

        <div className="bg-gray-900 p-6 rounded-2xl">
          <h3 className="text-xl font-bold mb-2">
            Recommended Role
          </h3>
          <p>AI/ML Engineer</p>
        </div>

        <div className="bg-gray-900 p-6 rounded-2xl">
          <h3 className="text-xl font-bold mb-2">
            Career Suggestion
          </h3>
          <p>
            Add deployment projects, cloud experience,
            and system design skills.
          </p>
        </div>

      </div>
    </div>
  );
}